version: '3.8'

services:
  backend:
    build:
      context: ./backend/blog_backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/blog_backend:/app
    ports:
      - "4000:4000"
    command: ["mix", "phx.server"]
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
